Repository anitab-org/anitab-forms-web, pull requests merged in 2021-02, with the labels that each got.

#57 UI: Design a 404 page for default redirects
  src/Routes.js
  src/components/ErrorPage.js
  src/styles/ErrorPage.css
Labels: Category: Coding, Category: User Interface, Status: Needs Testing

#79 docs: added license section in Readme.md
  README.md
Labels: Status: Needs Review

#88 [docs]: Move documentation from wiki to docusaurus
  README.md
  docs/.gitignore
  docs/README.md
  docs/babel.config.js
  docs/docs/2020-Bismita-Guha.md
  docs/docs/About-AnitaB.org-Open-Source.md
  docs/docs/Automation-and-Filtering.md
  docs/docs/Coding-Standards.md
  docs/docs/Commit-Message-Style-Guide.md
  docs/docs/Design-Guideline.md
  docs/docs/Export-Environment-Variables.md
  docs/docs/Fork,-Clone,-Remote-and-Pull-Request.md
  docs/docs/Forms.md
  docs/docs/Future-Ideas.md
  docs/docs/Getting-Started.md
  docs/docs/Home.md
  docs/docs/Main-Concepts.md
  docs/docs/Maintainer-Guidelines.md
  docs/docs/Tech-Stack.md
  docs/docs/Test-the-App.md
  docs/docs/User-Interface-Design.md
  docs/docusaurus.config.js
  docs/package.json
  docs/sidebars.js
  docs/src/css/custom.css
  docs/src/pages/index.js
  docs/src/pages/styles.module.css
  docs/static/.nojekyll
  docs/static/img/favicon.ico
  docs/static/img/logo.png
  docs/yarn.lock
Labels: Status: Needs Review

#93 docs: Improved Issue Templates and Pull Request Templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: Status: Needs Review

#92 fix: reload bug fix
  src/components/Menubar.js
  src/urls.js
Labels: Status: Ready to Merge

#90 Docs: Added Badges to readme
  README.md
Labels: Category: Documentation/Training, Status: Ready to Merge

#98 .github: deleted ISSUE_TEMPLATE and changed bug_report.md link (#96)
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/user-story.md
Labels: Status: Ready to Merge
